---
title: The Designery by Nikita Mehta Shah
timezone: Mumbai
collections:
  homepage_sections:
    title: Homepage Sections
    output: false
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: false
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:path"
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: work
    service:
url: http://www.thedesignery.in
permalink: pretty
description: The Designery is a multidisciplinary design house that specializes in
  brand strategy, creative solutions and communication design.
author: Nikita Mehta Shah
twitter: NikitaMehtaShah
image: "/uploads/favicons-04.png"
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: styles/
  style: compressed
social:
  name: The Designery by Nikita Mehta Shah
  links:
    - https://www.facebook.com/thedesigneryindia/
    - https://www.instagram.com/thedesignery_nikitamehtashah/
    - https://twitter.com/NikitaMehtaShah
